// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuny67_5hcPYauRiboodGYmgUfeVlHhaQ',
    appId: '1:825125131655:web:ced01a8dfa3b92dac96f22',
    messagingSenderId: '825125131655',
    projectId: 'shubhvite-2544d',
    authDomain: 'shubhvite-2544d.firebaseapp.com',
    storageBucket: 'shubhvite-2544d.appspot.com',
    measurementId: 'G-H8QGTCCT37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZYtDPoQtaUYf8edJOr2zMeSiYNk6MFqI',
    appId: '1:825125131655:android:8534c6878fbd958ec96f22',
    messagingSenderId: '825125131655',
    projectId: 'shubhvite-2544d',
    storageBucket: 'shubhvite-2544d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6f_bjhmW0VKi5GOnPHSpVY8Zq1eP2sr0',
    appId: '1:825125131655:ios:163c2a5ac738a1a2c96f22',
    messagingSenderId: '825125131655',
    projectId: 'shubhvite-2544d',
    storageBucket: 'shubhvite-2544d.appspot.com',
    iosBundleId: 'com.progressiveitservices.Amantrann',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6f_bjhmW0VKi5GOnPHSpVY8Zq1eP2sr0',
    appId: '1:825125131655:ios:eb5d460997b106ddc96f22',
    messagingSenderId: '825125131655',
    projectId: 'shubhvite-2544d',
    storageBucket: 'shubhvite-2544d.appspot.com',
    iosBundleId: 'com.example.getContacts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuny67_5hcPYauRiboodGYmgUfeVlHhaQ',
    appId: '1:825125131655:web:3f848edd80aa20b2c96f22',
    messagingSenderId: '825125131655',
    projectId: 'shubhvite-2544d',
    authDomain: 'shubhvite-2544d.firebaseapp.com',
    storageBucket: 'shubhvite-2544d.appspot.com',
    measurementId: 'G-CQL611TE9G',
  );
}
